// Generated by gencpp from file qcar_navigation/ConeDetectionArray.msg
// DO NOT EDIT!


#ifndef QCAR_NAVIGATION_MESSAGE_CONEDETECTIONARRAY_H
#define QCAR_NAVIGATION_MESSAGE_CONEDETECTIONARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <qcar_navigation/ConeDetection.h>

namespace qcar_navigation
{
template <class ContainerAllocator>
struct ConeDetectionArray_
{
  typedef ConeDetectionArray_<ContainerAllocator> Type;

  ConeDetectionArray_()
    : header()
    , detections()  {
    }
  ConeDetectionArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , detections(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::qcar_navigation::ConeDetection_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::qcar_navigation::ConeDetection_<ContainerAllocator> >> _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::qcar_navigation::ConeDetectionArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qcar_navigation::ConeDetectionArray_<ContainerAllocator> const> ConstPtr;

}; // struct ConeDetectionArray_

typedef ::qcar_navigation::ConeDetectionArray_<std::allocator<void> > ConeDetectionArray;

typedef boost::shared_ptr< ::qcar_navigation::ConeDetectionArray > ConeDetectionArrayPtr;
typedef boost::shared_ptr< ::qcar_navigation::ConeDetectionArray const> ConeDetectionArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qcar_navigation::ConeDetectionArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qcar_navigation::ConeDetectionArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::qcar_navigation::ConeDetectionArray_<ContainerAllocator1> & lhs, const ::qcar_navigation::ConeDetectionArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.detections == rhs.detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::qcar_navigation::ConeDetectionArray_<ContainerAllocator1> & lhs, const ::qcar_navigation::ConeDetectionArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace qcar_navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::qcar_navigation::ConeDetectionArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qcar_navigation::ConeDetectionArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qcar_navigation::ConeDetectionArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qcar_navigation::ConeDetectionArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qcar_navigation::ConeDetectionArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qcar_navigation::ConeDetectionArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qcar_navigation::ConeDetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef207be9d16b52faef039f081b24c602";
  }

  static const char* value(const ::qcar_navigation::ConeDetectionArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef207be9d16b52faULL;
  static const uint64_t static_value2 = 0xef039f081b24c602ULL;
};

template<class ContainerAllocator>
struct DataType< ::qcar_navigation::ConeDetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qcar_navigation/ConeDetectionArray";
  }

  static const char* value(const ::qcar_navigation::ConeDetectionArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qcar_navigation::ConeDetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header \n"
"\n"
"qcar_navigation/ConeDetection[] detections\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: qcar_navigation/ConeDetection\n"
"std_msgs/Header header\n"
"\n"
"uint8 UNKNOWN = 0\n"
"uint8 BLUE = 1\n"
"uint8 YELLOW = 2\n"
"uint8 ORANGE = 3\n"
"uint8 colour\n"
"\n"
"geometry_msgs/Vector3 direction\n"
"\n"
"float64 range\n"
"\n"
"geometry_msgs/Point position\n"
"\n"
"float64[4] position_covariance\n"
"\n"
"int32 bbox_x\n"
"int32 bbox_y\n"
"int32 bbox_w\n"
"int32 bbox_h\n"
"\n"
"int32 pixel_count\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::qcar_navigation::ConeDetectionArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qcar_navigation::ConeDetectionArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConeDetectionArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qcar_navigation::ConeDetectionArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qcar_navigation::ConeDetectionArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "detections: ";
    if (v.detections.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::qcar_navigation::ConeDetection_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.detections[i]);
    }
    if (v.detections.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // QCAR_NAVIGATION_MESSAGE_CONEDETECTIONARRAY_H
