// Generated by gencpp from file qcar_navigation/ConeDetection.msg
// DO NOT EDIT!


#ifndef QCAR_NAVIGATION_MESSAGE_CONEDETECTION_H
#define QCAR_NAVIGATION_MESSAGE_CONEDETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Point.h>

namespace qcar_navigation
{
template <class ContainerAllocator>
struct ConeDetection_
{
  typedef ConeDetection_<ContainerAllocator> Type;

  ConeDetection_()
    : header()
    , colour(0)
    , direction()
    , range(0.0)
    , position()
    , position_covariance()
    , bbox_x(0)
    , bbox_y(0)
    , bbox_w(0)
    , bbox_h(0)
    , pixel_count(0)  {
      position_covariance.assign(0.0);
  }
  ConeDetection_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , colour(0)
    , direction(_alloc)
    , range(0.0)
    , position(_alloc)
    , position_covariance()
    , bbox_x(0)
    , bbox_y(0)
    , bbox_w(0)
    , bbox_h(0)
    , pixel_count(0)  {
  (void)_alloc;
      position_covariance.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _colour_type;
  _colour_type colour;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _direction_type;
  _direction_type direction;

   typedef double _range_type;
  _range_type range;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef boost::array<double, 4>  _position_covariance_type;
  _position_covariance_type position_covariance;

   typedef int32_t _bbox_x_type;
  _bbox_x_type bbox_x;

   typedef int32_t _bbox_y_type;
  _bbox_y_type bbox_y;

   typedef int32_t _bbox_w_type;
  _bbox_w_type bbox_w;

   typedef int32_t _bbox_h_type;
  _bbox_h_type bbox_h;

   typedef int32_t _pixel_count_type;
  _pixel_count_type pixel_count;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(UNKNOWN)
  #undef UNKNOWN
#endif
#if defined(_WIN32) && defined(BLUE)
  #undef BLUE
#endif
#if defined(_WIN32) && defined(YELLOW)
  #undef YELLOW
#endif
#if defined(_WIN32) && defined(ORANGE)
  #undef ORANGE
#endif

  enum {
    UNKNOWN = 0u,
    BLUE = 1u,
    YELLOW = 2u,
    ORANGE = 3u,
  };


  typedef boost::shared_ptr< ::qcar_navigation::ConeDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qcar_navigation::ConeDetection_<ContainerAllocator> const> ConstPtr;

}; // struct ConeDetection_

typedef ::qcar_navigation::ConeDetection_<std::allocator<void> > ConeDetection;

typedef boost::shared_ptr< ::qcar_navigation::ConeDetection > ConeDetectionPtr;
typedef boost::shared_ptr< ::qcar_navigation::ConeDetection const> ConeDetectionConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qcar_navigation::ConeDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qcar_navigation::ConeDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::qcar_navigation::ConeDetection_<ContainerAllocator1> & lhs, const ::qcar_navigation::ConeDetection_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.colour == rhs.colour &&
    lhs.direction == rhs.direction &&
    lhs.range == rhs.range &&
    lhs.position == rhs.position &&
    lhs.position_covariance == rhs.position_covariance &&
    lhs.bbox_x == rhs.bbox_x &&
    lhs.bbox_y == rhs.bbox_y &&
    lhs.bbox_w == rhs.bbox_w &&
    lhs.bbox_h == rhs.bbox_h &&
    lhs.pixel_count == rhs.pixel_count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::qcar_navigation::ConeDetection_<ContainerAllocator1> & lhs, const ::qcar_navigation::ConeDetection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace qcar_navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::qcar_navigation::ConeDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qcar_navigation::ConeDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qcar_navigation::ConeDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qcar_navigation::ConeDetection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qcar_navigation::ConeDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qcar_navigation::ConeDetection_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qcar_navigation::ConeDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "41df40de730901088a49c65ee720b31e";
  }

  static const char* value(const ::qcar_navigation::ConeDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x41df40de73090108ULL;
  static const uint64_t static_value2 = 0x8a49c65ee720b31eULL;
};

template<class ContainerAllocator>
struct DataType< ::qcar_navigation::ConeDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qcar_navigation/ConeDetection";
  }

  static const char* value(const ::qcar_navigation::ConeDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qcar_navigation::ConeDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"uint8 UNKNOWN = 0\n"
"uint8 BLUE = 1\n"
"uint8 YELLOW = 2\n"
"uint8 ORANGE = 3\n"
"uint8 colour\n"
"\n"
"geometry_msgs/Vector3 direction\n"
"\n"
"float64 range\n"
"\n"
"geometry_msgs/Point position\n"
"\n"
"float64[4] position_covariance\n"
"\n"
"int32 bbox_x\n"
"int32 bbox_y\n"
"int32 bbox_w\n"
"int32 bbox_h\n"
"\n"
"int32 pixel_count\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::qcar_navigation::ConeDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qcar_navigation::ConeDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.colour);
      stream.next(m.direction);
      stream.next(m.range);
      stream.next(m.position);
      stream.next(m.position_covariance);
      stream.next(m.bbox_x);
      stream.next(m.bbox_y);
      stream.next(m.bbox_w);
      stream.next(m.bbox_h);
      stream.next(m.pixel_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConeDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qcar_navigation::ConeDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qcar_navigation::ConeDetection_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "colour: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.colour);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "direction: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.direction);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "range: ";
    Printer<double>::stream(s, indent + "  ", v.range);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "position: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "position_covariance: ";
    if (v.position_covariance.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.position_covariance.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.position_covariance[i]);
    }
    if (v.position_covariance.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bbox_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.bbox_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bbox_y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.bbox_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bbox_w: ";
    Printer<int32_t>::stream(s, indent + "  ", v.bbox_w);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bbox_h: ";
    Printer<int32_t>::stream(s, indent + "  ", v.bbox_h);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pixel_count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pixel_count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QCAR_NAVIGATION_MESSAGE_CONEDETECTION_H
