# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from qcar_navigation/ConeDetection.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class ConeDetection(genpy.Message):
  _md5sum = "41df40de730901088a49c65ee720b31e"
  _type = "qcar_navigation/ConeDetection"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

uint8 UNKNOWN = 0
uint8 BLUE = 1
uint8 YELLOW = 2
uint8 ORANGE = 3
uint8 colour

geometry_msgs/Vector3 direction

float64 range

geometry_msgs/Point position

float64[4] position_covariance

int32 bbox_x
int32 bbox_y
int32 bbox_w
int32 bbox_h

int32 pixel_count
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  # Pseudo-constants
  UNKNOWN = 0
  BLUE = 1
  YELLOW = 2
  ORANGE = 3

  __slots__ = ['header','colour','direction','range','position','position_covariance','bbox_x','bbox_y','bbox_w','bbox_h','pixel_count']
  _slot_types = ['std_msgs/Header','uint8','geometry_msgs/Vector3','float64','geometry_msgs/Point','float64[4]','int32','int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,colour,direction,range,position,position_covariance,bbox_x,bbox_y,bbox_w,bbox_h,pixel_count

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ConeDetection, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.colour is None:
        self.colour = 0
      if self.direction is None:
        self.direction = geometry_msgs.msg.Vector3()
      if self.range is None:
        self.range = 0.
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.position_covariance is None:
        self.position_covariance = [0.] * 4
      if self.bbox_x is None:
        self.bbox_x = 0
      if self.bbox_y is None:
        self.bbox_y = 0
      if self.bbox_w is None:
        self.bbox_w = 0
      if self.bbox_h is None:
        self.bbox_h = 0
      if self.pixel_count is None:
        self.pixel_count = 0
    else:
      self.header = std_msgs.msg.Header()
      self.colour = 0
      self.direction = geometry_msgs.msg.Vector3()
      self.range = 0.
      self.position = geometry_msgs.msg.Point()
      self.position_covariance = [0.] * 4
      self.bbox_x = 0
      self.bbox_y = 0
      self.bbox_w = 0
      self.bbox_h = 0
      self.pixel_count = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B7d().pack(_x.colour, _x.direction.x, _x.direction.y, _x.direction.z, _x.range, _x.position.x, _x.position.y, _x.position.z))
      buff.write(_get_struct_4d().pack(*self.position_covariance))
      _x = self
      buff.write(_get_struct_5i().pack(_x.bbox_x, _x.bbox_y, _x.bbox_w, _x.bbox_h, _x.pixel_count))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.direction is None:
        self.direction = geometry_msgs.msg.Vector3()
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 57
      (_x.colour, _x.direction.x, _x.direction.y, _x.direction.z, _x.range, _x.position.x, _x.position.y, _x.position.z,) = _get_struct_B7d().unpack(str[start:end])
      start = end
      end += 32
      self.position_covariance = _get_struct_4d().unpack(str[start:end])
      _x = self
      start = end
      end += 20
      (_x.bbox_x, _x.bbox_y, _x.bbox_w, _x.bbox_h, _x.pixel_count,) = _get_struct_5i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B7d().pack(_x.colour, _x.direction.x, _x.direction.y, _x.direction.z, _x.range, _x.position.x, _x.position.y, _x.position.z))
      buff.write(self.position_covariance.tostring())
      _x = self
      buff.write(_get_struct_5i().pack(_x.bbox_x, _x.bbox_y, _x.bbox_w, _x.bbox_h, _x.pixel_count))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.direction is None:
        self.direction = geometry_msgs.msg.Vector3()
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 57
      (_x.colour, _x.direction.x, _x.direction.y, _x.direction.z, _x.range, _x.position.x, _x.position.y, _x.position.z,) = _get_struct_B7d().unpack(str[start:end])
      start = end
      end += 32
      self.position_covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=4)
      _x = self
      start = end
      end += 20
      (_x.bbox_x, _x.bbox_y, _x.bbox_w, _x.bbox_h, _x.pixel_count,) = _get_struct_5i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
_struct_5i = None
def _get_struct_5i():
    global _struct_5i
    if _struct_5i is None:
        _struct_5i = struct.Struct("<5i")
    return _struct_5i
_struct_B7d = None
def _get_struct_B7d():
    global _struct_B7d
    if _struct_B7d is None:
        _struct_B7d = struct.Struct("<B7d")
    return _struct_B7d
